name: "Deploy to Laravel Forge"
description: "Deploy your site using Laravel Forge API"
author: "The Trybe"

inputs:
  forge_api_token:
    description: "Laravel Forge API Token"
    required: true
  deployment_file:
    description: "Path to the deployment config file"
    required: false
    default: "forge-deploy.yml"
  secrets:
    description: "Secret values to be replaced in the deployment config file"
    required: false

runs:
  using: "composite"
  steps:
    - name: Read and encode deployment config content
      id: read_forge_deploy
      run: |
        deploy_config=$(cat $DEPLOYMENT_FILE | base64 | tr -d '\n')
        echo "deploy_config=$deploy_config" >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        DEPLOYMENT_FILE: ${{ inputs.deployment_file }}
      continue-on-error: false

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - uses: actions/checkout@v4
      with:
        repository: the-trybe/forge-deployment-scripts
        ref: main

    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
      continue-on-error: false

    - name: Decode and Save deploy_config
      run: |
        echo "${{ steps.read_forge_deploy.outputs.deploy_config }}" | base64 --decode > $DEPLOYMENT_FILE  # Decoding the base64 content back to YAML
      shell: bash
      continue-on-error: false
      env:
        DEPLOYMENT_FILE: ${{ inputs.deployment_file }}

    - name: Deploy to Laravel Forge
      run: python3 deploy.py
      shell: bash
      env:
        FORGE_API_TOKEN: ${{ inputs.forge_api_token }}
        DEPLOYMENT_FILE: ${{ inputs.deployment_file }}
        SECRETS: ${{ inputs.secrets }}
