name: "Deploy to Laravel Forge"
description: "Deploy your site using Laravel Forge API"
author: "The Trybe"

inputs:
  forge_api_token:
    description: "Laravel Forge API Token"
    required: true
  deployment_file:
    description: "Path to the deployment config file"
    required: false
    default: "forge-deploy.yml"
  secrets:
    description: "Secret values to be replaced in the deployment config file"
    required: false

  debug:
    description: "Enable debug mode"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - uses: actions/checkout@v4
      with:
        repository: the-trybe/forge-deployment-scripts
        path: forge-deployment-scripts

    - name: Install Dependencies
      run: pip install -r forge-deployment-scripts/requirements.txt
      shell: bash
      continue-on-error: false

    - name: Deploy to Laravel Forge
      run: python3 forge-deployment-scripts/deploy.py
      shell: bash
      env:
        FORGE_API_TOKEN: ${{ inputs.forge_api_token }}
        DEPLOYMENT_FILE: ${{ inputs.deployment_file }}
        SECRETS: ${{ inputs.secrets }}
        DEBUG: ${{ inputs.debug }}
